services:
  - docker

script:
  - export REPO=$DOCKER_USER/$DOCKER_REPO
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO
